-- Agrega IP_ORIGEN en SEG_AUDITORIA_DET para auditoría de logins.
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'CONSULTORIO'
       AND TABLE_NAME = 'SEG_AUDITORIA_DET'
       AND COLUMN_NAME = 'IP_ORIGEN';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CONSULTORIO.SEG_AUDITORIA_DET ADD (IP_ORIGEN VARCHAR2(45 CHAR))';
    END IF;
END;
/
