/*
  Script base de seguridad para CONSULTORIO (Oracle 11g)
  Basado en la especificación funcional compartida por el usuario.
  Incluye tablas core, secuencias y triggers para SEG_USUARIO, SEG_ROL,
  SEG_PERMISO, SEG_USUARIO_ROL, SEG_ROL_PERMISO, SEG_SESION,
  SEG_BITACORA_ACCESO y SEG_AUDITORIA_DET.
*/

CREATE TABLE CONSULTORIO.SEG_USUARIO (
    ID_USUARIO                NUMBER(10,0)       NOT NULL,
    USERNAME                  VARCHAR2(50 CHAR)  NOT NULL,
    CLAVE_HASH                VARCHAR2(255 CHAR) NOT NULL,
    ALGORITMO_HASH            VARCHAR2(30 CHAR)  DEFAULT 'SHA-256' NOT NULL,
    NOMBRE_VISIBLE            VARCHAR2(150 CHAR) NOT NULL,
    EMAIL                     VARCHAR2(150 CHAR),
    NO_PERSONA                NUMBER(10,0),
    NO_EMP                    NUMBER(10,0),
    NO_CEDULA                 VARCHAR2(20 CHAR),
    TIPO_USUARIO              VARCHAR2(20 CHAR)  DEFAULT 'INTERNO' NOT NULL,
    ACTIVO                    CHAR(1 CHAR)       DEFAULT 'S' NOT NULL,
    BLOQUEADO                 CHAR(1 CHAR)       DEFAULT 'N' NOT NULL,
    INTENTOS_FALLIDOS         NUMBER(3,0)        DEFAULT 0 NOT NULL,
    FECHA_BLOQUEO             DATE,
    FECHA_ULTIMO_LOGIN        DATE,
    FECHA_ULTIMO_CAMBIO_CLAVE DATE,
    REQUIERE_CAMBIO_CLAVE     CHAR(1 CHAR)       DEFAULT 'S' NOT NULL,
    OBSERVACION               VARCHAR2(500 CHAR),
    F_CREACION                DATE               DEFAULT SYSDATE NOT NULL,
    USR_CREACION              VARCHAR2(30 CHAR),
    F_ACTUALIZACION           DATE,
    USR_ACTUALIZACION         VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_SEG_USUARIO_01 UNIQUE (USERNAME)
);

CREATE TABLE CONSULTORIO.SEG_ROL (
    ID_ROL              NUMBER(10,0)       NOT NULL,
    CODIGO              VARCHAR2(50 CHAR)  NOT NULL,
    NOMBRE              VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION         VARCHAR2(500 CHAR),
    ACTIVO              CHAR(1 CHAR)       DEFAULT 'S' NOT NULL,
    ES_SISTEMA          CHAR(1 CHAR)       DEFAULT 'N' NOT NULL,
    F_CREACION          DATE               DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    F_ACTUALIZACION     DATE,
    USR_ACTUALIZACION   VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT UK_SEG_ROL_01 UNIQUE (CODIGO)
);

CREATE TABLE CONSULTORIO.SEG_PERMISO (
    ID_PERMISO          NUMBER(10,0)       NOT NULL,
    CODIGO              VARCHAR2(80 CHAR)  NOT NULL,
    MODULO              VARCHAR2(50 CHAR)  NOT NULL,
    RECURSO             VARCHAR2(80 CHAR)  NOT NULL,
    ACCION              VARCHAR2(50 CHAR)  NOT NULL,
    NOMBRE              VARCHAR2(120 CHAR) NOT NULL,
    DESCRIPCION         VARCHAR2(500 CHAR),
    ACTIVO              CHAR(1 CHAR)       DEFAULT 'S' NOT NULL,
    F_CREACION          DATE               DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    F_ACTUALIZACION     DATE,
    USR_ACTUALIZACION   VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_PERMISO PRIMARY KEY (ID_PERMISO),
    CONSTRAINT UK_SEG_PERMISO_01 UNIQUE (CODIGO)
);

CREATE TABLE CONSULTORIO.SEG_USUARIO_ROL (
    ID_USUARIO_ROL      NUMBER(10,0)      NOT NULL,
    ID_USUARIO          NUMBER(10,0)      NOT NULL,
    ID_ROL              NUMBER(10,0)      NOT NULL,
    FECHA_DESDE         DATE              DEFAULT SYSDATE NOT NULL,
    FECHA_HASTA         DATE,
    ACTIVO              CHAR(1 CHAR)      DEFAULT 'S' NOT NULL,
    F_CREACION          DATE              DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    F_ACTUALIZACION     DATE,
    USR_ACTUALIZACION   VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_USUARIO_ROL PRIMARY KEY (ID_USUARIO_ROL),
    CONSTRAINT FK_SEG_UR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CONSULTORIO.SEG_USUARIO (ID_USUARIO),
    CONSTRAINT FK_SEG_UR_ROL FOREIGN KEY (ID_ROL) REFERENCES CONSULTORIO.SEG_ROL (ID_ROL)
);

CREATE TABLE CONSULTORIO.SEG_ROL_PERMISO (
    ID_ROL_PERMISO      NUMBER(10,0)      NOT NULL,
    ID_ROL              NUMBER(10,0)      NOT NULL,
    ID_PERMISO          NUMBER(10,0)      NOT NULL,
    ACTIVO              CHAR(1 CHAR)      DEFAULT 'S' NOT NULL,
    F_CREACION          DATE              DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    F_ACTUALIZACION     DATE,
    USR_ACTUALIZACION   VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_ROL_PERMISO PRIMARY KEY (ID_ROL_PERMISO),
    CONSTRAINT FK_SEG_RP_ROL FOREIGN KEY (ID_ROL) REFERENCES CONSULTORIO.SEG_ROL (ID_ROL),
    CONSTRAINT FK_SEG_RP_PERM FOREIGN KEY (ID_PERMISO) REFERENCES CONSULTORIO.SEG_PERMISO (ID_PERMISO)
);

CREATE TABLE CONSULTORIO.SEG_SESION (
    ID_SESION           NUMBER(10,0)       NOT NULL,
    ID_USUARIO          NUMBER(10,0)       NOT NULL,
    TOKEN_SESION        VARCHAR2(200 CHAR) NOT NULL,
    FECHA_LOGIN         DATE               NOT NULL,
    FECHA_ULTIMA_ACT    DATE               NOT NULL,
    FECHA_EXPIRACION    DATE               NOT NULL,
    FECHA_LOGOUT        DATE,
    IP_ORIGEN           VARCHAR2(45 CHAR),
    NAVEGADOR           VARCHAR2(300 CHAR),
    ACTIVA              CHAR(1 CHAR)       DEFAULT 'S' NOT NULL,
    F_CREACION          DATE               DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_SESION PRIMARY KEY (ID_SESION),
    CONSTRAINT FK_SEG_SESION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CONSULTORIO.SEG_USUARIO (ID_USUARIO)
);

CREATE TABLE CONSULTORIO.SEG_BITACORA_ACCESO (
    ID_BITACORA         NUMBER(10,0)       NOT NULL,
    ID_USUARIO          NUMBER(10,0),
    USERNAME_INTENTADO  VARCHAR2(50 CHAR),
    ID_SESION           NUMBER(10,0),
    EVENTO              VARCHAR2(30 CHAR)  NOT NULL,
    EXITOSO             CHAR(1 CHAR)       DEFAULT 'N' NOT NULL,
    FECHA_EVENTO        DATE               DEFAULT SYSDATE NOT NULL,
    DETALLE             VARCHAR2(1000 CHAR),
    F_CREACION          DATE               DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_BITACORA_ACCESO PRIMARY KEY (ID_BITACORA)
);

CREATE TABLE CONSULTORIO.SEG_AUDITORIA_DET (
    ID_AUDITORIA        NUMBER(10,0)       NOT NULL,
    ID_USUARIO          NUMBER(10,0),
    ID_SESION           NUMBER(10,0),
    MODULO              VARCHAR2(60 CHAR)  NOT NULL,
    PROCESO             VARCHAR2(120 CHAR) NOT NULL,
    ENTIDAD             VARCHAR2(80 CHAR)  NOT NULL,
    ID_REGISTRO         VARCHAR2(80 CHAR),
    OPERACION           CHAR(1 CHAR)       NOT NULL,
    VALOR_ANTERIOR      CLOB,
    VALOR_NUEVO         CLOB,
    FECHA_EVENTO        DATE               DEFAULT SYSDATE NOT NULL,
    F_CREACION          DATE               DEFAULT SYSDATE NOT NULL,
    USR_CREACION        VARCHAR2(30 CHAR),
    CONSTRAINT PK_SEG_AUDITORIA_DET PRIMARY KEY (ID_AUDITORIA)
);

CREATE SEQUENCE CONSULTORIO.SQ_SEG_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_ROL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_PERMISO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_USUARIO_ROL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_ROL_PERMISO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_SESION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_BITACORA_ACCESO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CONSULTORIO.SQ_SEG_AUDITORIA_DET START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
