package ec.gob.igm.rrhh.consultorio.web.mapper;

import java.util.Date;

import ec.gob.igm.rrhh.consultorio.domain.model.DatEmpleado;
import ec.gob.igm.rrhh.consultorio.domain.model.FichaOcupacional;
import ec.gob.igm.rrhh.consultorio.domain.model.PersonaAux;
import ec.gob.igm.rrhh.consultorio.domain.model.SignosVitales;
import ec.gob.igm.rrhh.consultorio.service.Step1FichaService;
import jakarta.ejb.Stateless;

@Stateless
public class Step1CommandAssembler {

    public Step1FichaService.Step1Command toCommand(
            FichaOcupacional ficha,
            DatEmpleado empleadoSel,
            PersonaAux personaAux,
            SignosVitales signos,
            Integer noPersonaSel,
            Date fechaAtencion,
            String tipoEval,
            String paStr,
            Double temp,
            Integer fc,
            Integer fr,
            Integer satO2,
            Double peso,
            Double tallaCm,
            Double perimetroAbd,
            Boolean apEmbarazada,
            Boolean apDiscapacidad,
            Boolean apCatastrofica,
            Boolean apLactancia,
            Boolean apAdultoMayor,
            String antClinicoQuirurgico,
            String antFamiliares,
            String condicionEspecial,
            String autorizaTransfusion,
            String tratamientoHormonal,
            String tratamientoHormonalCual,
            String examenReproMasculino,
            Integer tiempoReproMasculino,
            String ginecoExamen1,
            String ginecoTiempo1,
            String ginecoResultado1,
            String ginecoExamen2,
            String ginecoTiempo2,
            String ginecoResultado2,
            String ginecoObservacion,
            Date fum,
            Integer gestas,
            Integer partos,
            Integer cesareas,
            Integer abortos,
            String planificacion,
            String planificacionCual,
            String discapTipo,
            String discapDesc,
            Integer discapPorc,
            String catasDiagnostico,
            Boolean catasCalificada,
            String nRealizaEvaluacion,
            String nRelacionTrabajo,
            String nObsRetiro,
            Integer[] consTiempoConsumoMeses,
            Boolean[] consExConsumidor,
            Integer[] consTiempoAbstinenciaMeses,
            Boolean[] consNoConsume,
            String consOtrasCual,
            String[] afCual,
            String[] afTiempo,
            String[] medCual,
            Integer[] medCant,
            String consumoVidaCondObs,
            String usuario) {
        return new Step1FichaService.Step1Command(
                ficha,
                empleadoSel,
                personaAux,
                signos,
                noPersonaSel,
                fechaAtencion,
                tipoEval,
                paStr,
                temp,
                fc,
                fr,
                satO2,
                peso,
                tallaCm,
                perimetroAbd,
                apEmbarazada,
                apDiscapacidad,
                apCatastrofica,
                apLactancia,
                apAdultoMayor,
                antClinicoQuirurgico,
                antFamiliares,
                condicionEspecial,
                autorizaTransfusion,
                tratamientoHormonal,
                tratamientoHormonalCual,
                examenReproMasculino,
                tiempoReproMasculino,
                ginecoExamen1,
                ginecoTiempo1,
                ginecoResultado1,
                ginecoExamen2,
                ginecoTiempo2,
                ginecoResultado2,
                ginecoObservacion,
                fum,
                gestas,
                partos,
                cesareas,
                abortos,
                planificacion,
                planificacionCual,
                discapTipo,
                discapDesc,
                discapPorc,
                catasDiagnostico,
                catasCalificada,
                nRealizaEvaluacion,
                nRelacionTrabajo,
                nObsRetiro,
                consTiempoConsumoMeses,
                consExConsumidor,
                consTiempoAbstinenciaMeses,
                consNoConsume,
                consOtrasCual,
                afCual,
                afTiempo,
                medCual,
                medCant,
                consumoVidaCondObs,
                usuario);
    }
}
